// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdN_9HJRPRSgVIhtDrEcwZiYK9AAof6VA',
    appId: '1:1062597678372:web:e1402bff26a8d19a8f4fb1',
    messagingSenderId: '1062597678372',
    projectId: 'neuricax',
    authDomain: 'neuricax.firebaseapp.com',
    storageBucket: 'neuricax.firebasestorage.app',
    measurementId: 'G-X1QHTY7PND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5nxU3MJZownfMy44YTPJXPauObao2h4k',
    appId: '1:1062597678372:android:4d9be4a3cd29e46a8f4fb1',
    messagingSenderId: '1062597678372',
    projectId: 'neuricax',
    storageBucket: 'neuricax.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWUqNDkEcHTQaWyUTXwxJuZ6mj1s6u52A',
    appId: '1:1062597678372:ios:02af7bd8f0b7247a8f4fb1',
    messagingSenderId: '1062597678372',
    projectId: 'neuricax',
    storageBucket: 'neuricax.firebasestorage.app',
    iosBundleId: 'com.aprilsunmedia.neuricax',
  );
}
